build.gradle
src/main/java/org/oreo/smore/domain/user/UserController.java
src/main/java/org/oreo/smore/domain/user/UserService.java
src/main/java/org/oreo/smore/domain/user/dto/request/UserUpdateRequest.java
src/main/java/org/oreo/smore/domain/user/dto/request/UserUpdateResponse.java
src/main/java/org/oreo/smore/global/common/CloudStorageManager.java
src/main/java/org/oreo/smore/global/config/BlobStorageConfig.java
src/main/resources/application.yml

Summary
프로필 수정을 구현했습니다.
Changes
feat: 프로필 수정 구현
feat: 프로필 수정 Controller 구현
feat: BlobStorageConfig 설정
Details
입력 형식과 userId에 대한 검증 구현
이미지 업로드 유틸 구현 및 프로필 수정 구현

Feat: update profile

---

src/main/java/org/oreo/smore/domain/studytime/StudyTime.java
src/main/java/org/oreo/smore/domain/studytime/StudyTimeController.java
src/main/java/org/oreo/smore/domain/studytime/StudyTimeRepository.java
src/main/java/org/oreo/smore/domain/studytime/StudyTimeService.java
src/main/java/org/oreo/smore/domain/user/UserController.java

공부 시작을 구현했습니다.
feat: 공부 시작 구현
fix: UserController URL 수정
feat: 공부 시작 Controller 구현
UserController URL 수정에서 @RequestMapping("/v1")를 삭제했습니다.

Feat: study start

---

src/main/java/org/oreo/smore/domain/auth/oauth/OAuth2SuccessHandler.java
src/main/java/org/oreo/smore/global/config/SecurityConfig.java

- 원인: redirect url을 주입 받는 클래스가 빈 등록이 안됨
- 해결: 빈 등록 주입을 통한 연동

Hotfix: redirect url 주입 오류 수정

---

src/main/java/org/oreo/smore/domain/participant/Participant.java
src/main/java/org/oreo/smore/domain/participant/ParticipantRepository.java
src/main/java/org/oreo/smore/domain/participant/ParticipantService.java
src/main/java/org/oreo/smore/domain/participant/exception/ParticipantException.java
src/main/java/org/oreo/smore/domain/studyroom/StudyRoomCreationService.java
src/main/java/org/oreo/smore/domain/video/controller/VideoCallController.java
src/test/java/org/oreo/smore/domain/participant/ParticipantTest.java

스터디룸 나가기 삭제 구현
feat: 스터디룸 나가기 구현
feat: 스터디룸 삭제 구현
방장이 스터디룸을 나가면 방 삭제 로직
참가자가 스터디룸을 나가면 방 나가기 로직으로 구현

feat: 스터디룸 CRUD 추가

---

src/main/java/org/oreo/smore/domain/studyroom/StudyRoomController.java
src/main/java/org/oreo/smore/domain/studyroom/StudyRoomService.java
src/main/java/org/oreo/smore/domain/studyroom/dto/StudyRoomDetailResponse.java
src/main/java/org/oreo/smore/domain/studytime/StudyTimeController.java
src/main/java/org/oreo/smore/domain/user/UserController.java
src/main/java/org/oreo/smore/domain/user/UserService.java
src/main/java/org/oreo/smore/domain/user/dto/request/UserUpdateRequest.java

스터디룸 상세 조회를 구현 했습니다.
fix: user id 불일치 상태코드 수정
feat: 악의적인 닉네임 중복 방지 구현
feat: 목표 공부 시간 분으로 확장
feat: 스터디룸 상세 조회 Controller 구현
feat: 스터디룸 상세 조회 구현
각종 추가 기능들도 구현 했습니다.

Feat: studyroom details

---

src/main/java/org/oreo/smore/domain/studyroom/StudyRoomController.java
src/main/java/org/oreo/smore/domain/studyroom/StudyRoomService.java
src/main/java/org/oreo/smore/domain/studyroom/dto/RecentStudyRoomsResponse.java
src/main/java/org/oreo/smore/domain/studyroom/dto/StudyRoomDetailResponse.java

최근 3개 참여 스터디방 조회를 구현 했습니다.
fix: wrapper pattern 적용
feat: 최근 참여 스터디룸 조회 Controller 구현
feat: 최근 참여 3개 스터디방 조회 구현
wrapper pattern을 적용하여 data로 감쌌습니다.

Feat: recent study

---

src/main/java/org/oreo/smore/domain/auth/AuthController.java
src/main/java/org/oreo/smore/domain/focusrecord/FocusRecordService.java
src/main/java/org/oreo/smore/domain/focusrecord/dto/FocusRecordsResponse.java
src/main/java/org/oreo/smore/domain/studytime/StudyTimeService.java
src/main/java/org/oreo/smore/domain/studytime/dto/response/StudyTimeStatisticsResponse.java
src/main/java/org/oreo/smore/domain/user/UserService.java
src/main/java/org/oreo/smore/domain/user/dto/response/UserInfoResponse.java
src/main/java/org/oreo/smore/domain/user/dto/response/UserUpdateResponse.java

Hotfix: 데이터 wrapping 오류 해결

---

src/main/java/org/oreo/smore/domain/studyroom/dto/StudyRoomInfoReadResponse.java

스터디룸 리스트 조회 데이터에 description 추가
- StudyRoomInfoReadResponse 클래스의 내부 필드 추가
- StudyRoomInfoReadResponse.of 메서드 일부 수정

Hotfix: 스터디룸 리스트 조회 데이터 description 추가

---

src/main/java/org/oreo/smore/domain/point/Point.java
src/main/java/org/oreo/smore/domain/point/PointController.java
src/main/java/org/oreo/smore/domain/point/PointRepository.java
src/main/java/org/oreo/smore/domain/point/PointService.java
src/main/java/org/oreo/smore/domain/point/dto/response/TotalPointsResponse.java

포인트 조회를 추가했습니다.
feat: Point Entity 설정
feat: 포인트 조회 Controller 구현
feat: 포인트 조회 구현

Feat: get points

---

src/main/java/org/oreo/smore/domain/participant/ParticipantService.java
src/main/java/org/oreo/smore/domain/participant/dto/IndividualParticipantResponse.java
src/main/java/org/oreo/smore/domain/participant/dto/MuteAllResponse.java
src/main/java/org/oreo/smore/domain/participant/dto/UpdatePersonalStatusRequest.java
src/main/java/org/oreo/smore/domain/participant/dto/UpdatePersonalStatusResponse.java
src/main/java/org/oreo/smore/domain/video/controller/VideoCallController.java
src/main/java/org/oreo/smore/domain/video/dto/JoinRoomRequest.java
src/main/java/org/oreo/smore/domain/video/validator/StudyRoomValidator.java
src/test/java/org/oreo/smore/domain/focusrecord/FocusRecordServiceTest.java
src/test/java/org/oreo/smore/domain/participant/ParticipantServiceMuteAllTest.java
src/test/java/org/oreo/smore/domain/participant/ParticipantServiceTest.java
src/test/java/org/oreo/smore/domain/participant/ParticipantServiceUpdateTest.java
src/test/java/org/oreo/smore/domain/participant/ParticipantStatusTest.java
src/test/java/org/oreo/smore/domain/participant/VideoCallControllerParticipantStatusTest.java
src/test/java/org/oreo/smore/domain/participant/VideoCallControllerStatusTest.java
src/test/java/org/oreo/smore/domain/video/controller/BanParticipantTest.java
src/test/java/org/oreo/smore/domain/video/controller/VideoCallControllerIndividualTest.java
src/test/java/org/oreo/smore/domain/video/controller/VideoCallControllerUpdateTest.java

- 참가자 개인 상태 조회
- 카메라 마이크 상태 설정

Feat: 참가자 개인 상태 조회, 카메라 마이크 설정 기능 추가

---

src/main/java/org/oreo/smore/domain/participant/ParticipantService.java
src/main/java/org/oreo/smore/domain/point/PointController.java
src/main/java/org/oreo/smore/domain/point/PointService.java
src/main/java/org/oreo/smore/domain/point/dto/response/OreoDrawResponse.java

포인트 조회를 추가했습니다.
feat: 포인트 사용 Controller 구현
feat: 포인트 사용 구현
fix: 오늘 공부 시간 변경
스터디룸에서의 오늘 공부 시간을 분에서 초로 변경

Feat: use points

---

src/main/java/org/oreo/smore/domain/participant/dto/MuteAllRequest.java
src/main/java/org/oreo/smore/domain/video/controller/VideoCallController.java
src/main/java/org/oreo/smore/global/exception/GlobalExceptionHandler.java
src/main/java/org/oreo/smore/global/exception/IncorrectPasswordException.java
src/main/java/org/oreo/smore/global/exception/NotRoomOwnerException.java
src/main/java/org/oreo/smore/global/exception/RoomCapacityExceededException.java
src/main/java/org/oreo/smore/global/exception/RoomNotFoundException.java
src/main/java/org/oreo/smore/global/exception/SelfBanAttemptException.java
src/main/java/org/oreo/smore/global/exception/UnauthorizedException.java
src/main/java/org/oreo/smore/global/exception/UserNotParticipantException.java
src/test/java/org/oreo/smore/domain/participant/ParticipantServiceTest.java
src/test/java/org/oreo/smore/domain/participant/VideoCallControllerParticipantStatusTest.java
src/test/java/org/oreo/smore/domain/studyroom/StudyRoomControllerTest.java
src/test/java/org/oreo/smore/domain/video/controller/BanParticipantTest.java
src/test/java/org/oreo/smore/domain/video/controller/VideoCallControllerIntegrationTest.java
src/test/java/org/oreo/smore/domain/video/controller/VideoCallControllerLeaveTest.java

- 무엇을 변경했는지 명확하게 설명해 주세요.
- Closes #123 (Github 이슈)
- Jira: [Jira 이슈 번호]()
1. 페이지 접속
2. 버튼 클릭
3. 결과 확인
1. 리뷰어에게 참고가 될만한 정보나 추가 설명 부탁드립니다.
2. 사용하지 않는 메뉴는 삭제해주세요.

Hotfix: 예외 분기처리 추가

---

src/main/java/org/oreo/smore/domain/studyroom/dto/StudyRoomInfoReadResponse.java

Hotfix: pomodoro 조회 수정

---

src/main/java/org/oreo/smore/domain/studyroom/StudyRoomCategory.java
src/main/java/org/oreo/smore/domain/studyroom/StudyRoomService.java
src/main/java/org/oreo/smore/domain/studyroom/dto/StudyRoomInfoReadResponse.java
src/test/java/org/oreo/smore/domain/studyroom/dto/CreateStudyRoomRequestTest.java

hotfix: 방 목록 데이터 enum 값 한글 변환

---

src/main/java/org/oreo/smore/domain/focusrecord/FocusRecordService.java

- focus-record 없을때 오류 수정
- 오류가 아닌, 빈 값으로 처리

Hotfix: 레코드 수정

---

src/main/java/org/oreo/smore/global/config/SecurityConfig.java

Hotfix: webhook을 위한 config 열기

---

src/main/java/org/oreo/smore/domain/participant/ParticipantRepository.java
src/main/java/org/oreo/smore/domain/studyroom/StudyRoomRepository.java
src/main/java/org/oreo/smore/domain/user/UserRepository.java
src/main/java/org/oreo/smore/domain/webhook/WebhookController.java
src/main/java/org/oreo/smore/domain/webhook/WebhookService.java

feat: webhook 유저 나가기 구현

---

src/main/java/org/oreo/smore/domain/studyroom/StudyRoomService.java
src/main/java/org/oreo/smore/domain/studyroom/dto/RecentStudyRoomsResponse.java

hotfix: isDelete 이름 수정

---

src/main/java/org/oreo/smore/domain/participant/ParticipantService.java

- 무엇을 변경했는지 명확하게 설명해 주세요.
- Closes #123 (Github 이슈)
- Jira: [Jira 이슈 번호]()
1. 페이지 접속
2. 버튼 클릭
3. 결과 확인
1. 리뷰어에게 참고가 될만한 정보나 추가 설명 부탁드립니다.
2. 사용하지 않는 메뉴는 삭제해주세요.

hotfix: soft delete

---

src/main/java/org/oreo/smore/domain/webhook/WebhookService.java

- 무엇을 변경했는지 명확하게 설명해 주세요.
- Closes #123 (Github 이슈)
- Jira: [Jira 이슈 번호]()
1. 페이지 접속
2. 버튼 클릭
3. 결과 확인
1. 리뷰어에게 참고가 될만한 정보나 추가 설명 부탁드립니다.
2. 사용하지 않는 메뉴는 삭제해주세요.

Hotfix: 새로고침 뒤로가기 webhook 수정
